@startuml

class Link {
    +{static} all()
    +{static} create(url, title)
}

class DatabaseConnection <<Singleton>>  {
    +{static} connection
    +{static} setup()
    +{static} query()
}

Controller --> Link: all links
Link --> Controller: [collection of links]
Link --> DatabaseConnection

@enduml
