@startuml

class bookmark {
    +{static} all()
    +{static} create(url, title)
    +{static} delete(id)
    +{static} a_url?(string)
}

class DatabaseConnection <<Singleton>>  {
    +{static} connection
    +{static} setup()
    +{static} query()
}

Controller --> bookmark: all bookmarks
Controller --> Index
bookmark --> Controller: [collection of bookmarks]
bookmark --> DatabaseConnection

@enduml
